---
## Install & Enable Nginx
- name: Install nginx.
  shell: amazon-linux-extras install nginx1.12

- name: Enable nginx service.
  systemd:
    name: nginx
    enabled: yes

- name: Restart Nginx Service.
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
