---
- hosts: nginx_php72fpm_prd_servers
  become: yes
  roles:
    - common
    - nginx
    - php72
    - zabbix_agent
    - fluentd

- hosts: nginx_php72fpm_stg_servers
  become: yes
  roles:
    - common
    - nginx
    - php72
    - zabbix_agent
    - fluentd

- hosts: nginx_php72fpm_dev_servers
  become: yes
  roles:
    - common
    - nginx
    - php72
    - zabbix_agent
    - fluentd
