---
## Set Hostname
- name: Set Hostname
  hostname:
    name: "{{env}}_{{role}}_{{server_oct3}}_{{server_oct4}}"

## Yum Update
- name: Yum update.
  yum:
    name: '*'
    state: latest

## Install Epel Repository
- name: Yum install epel repository.
  shell: amazon-linux-extras install epel

## Install Git Repository
- name: Yum install git.
  yum:
    name: git
    state: latest

## Change Time Zone
- name: Set timezone to Asia/Tokyo.
  timezone:
    name: "{{ timezone }}"

## Add Configure Logrotate (*option)
