---
## Install & Enable PHP 7.2
- name: Install PHP 7.2.
  shell: amazon-linux-extras install php7.2

- name: Install PHP modules.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php-mbstring
    - php-devel
    - php-opcache
    - php-process
    - php-xml
    - php-gd
    - php-pecl-zip 

- name: Install APCu module & config.
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'apcu.so',     dest: '/usr/lib64/php/modules/apcu.so' }
    - { src: '40-apcu.ini', dest: '/etc/php.d/40-apcu.ini' }

- name: Change mode APCu module
  file:
    path: '/usr/lib64/php/modules/apcu.so'
    mode: 0755

- name: Install Composer
  copy:
    src:  'composer'
    dest: '/usr/local/bin/composer'

- name: Change mode Composer
  file:
    path: '/usr/local/bin/composer'
    mode: 0755

- name: Set php72-fpm configure
  template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "php.ini.j2",        dest: "/etc/php.ini"} 
    - { src: "10-opcache.ini.j2", dest: "/etc/php.d/10-opcache.ini"} 
    - { src: "www.conf.j2",       dest: "/etc/php-fpm.d/www.conf"} 

- name: Change owner dir.
  file: 
    path:  "{{item.path}}"
    owner: "{{item.owner}}"
  with_items:
    - { path: '/var/log/php-fpm',       owner: 'nginx' }
    - { path: '/var/lib/php/opcache',   owner: 'nginx' }
    - { path: '/var/lib/php/session',   owner: 'nginx' }
    - { path: '/var/lib/php/wsdlcache', owner: 'nginx' }
    - { path: '/var/lib/php/peclxml',   owner: 'nginx' }

- name: Enable PHP-FPM Service.
  systemd:
    name: php-fpm 
    enabled: yes

- name: Restart PHP-FPM Service.
  systemd:
    name: php-fpm
    state: restarted
    daemon_reload: yes
